### ISSUE TITLE
2K resolution

### ISSUE THREAD

**Issue by brusvv** [ucarno/ow-picker#1]
Hello!
It would be nice if this screen resolution appeared, yes, it's not as popular as Full HD, but not the most niche either. What information do you need? I can help you and tell point of pixels.

**Comment by brusvv** [comment]
Can you update it for OW2 please?

**Comment by ucarno** [comment]
> Can you update it for OW2 please?

OW2 has better anti-cheat and may consider such app a cheating software, so if app does not try to hide itself by sending raw packages, it can get you banned
